-- Update ALL products with the same 4 image URLs
-- This script adds the same 4 images to every product in your database

UPDATE products 
SET images = '[
  "https://aqvcyyhuqcjnhohaclib.supabase.co/storage/v1/object/sign/categories/jhabla_shorts_category.webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81OWNhOGQyOC00MGM3LTQwOGEtYjZmOC04NjcxMmVmNzFhM2IiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJjYXRlZ29yaWVzL2poYWJsYV9zaG9ydHNfY2F0ZWdvcnkud2VicCIsImlhdCI6MTc1OTIwODYwMywiZXhwIjoxNzkwNzQ0NjAzfQ.vc_6Lk343rig3oW4CwVTLfVo2JVWmOYZKr-7bXMtx2s",
  "https://aqvcyyhuqcjnhohaclib.supabase.co/storage/v1/object/sign/categories/jhabla_category.webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81OWNhOGQyOC00MGM3LTQwOGEtYjZmOC04NjcxMmVmNzFhM2IiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJjYXRlZ29yaWVzL2poYWJsYV9jYXRlZ29yeS53ZWJwIiwiaWF0IjoxNzU5MjA4NjIyLCJleHAiOjE3OTA3NDQ2MjJ9.SDYMapGhtVMu4kvNDJABR6Tk1wGd4dj0NaQOcJMYV7c",
  "https://aqvcyyhuqcjnhohaclib.supabase.co/storage/v1/object/sign/categories/nappies_category.webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81OWNhOGQyOC00MGM3LTQwOGEtYjZmOC04NjcxMmVmNzFhM2IiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJjYXRlZ29yaWVzL25hcHBpZXNfY2F0ZWdvcnkud2VicCIsImlhdCI6MTc1OTIwODYzNiwiZXhwIjoxNzkwNzQ0NjM2fQ.1woLmtxjvXhPltCeUkqVpZx2FFvAQ0kp_F3UGmPKzLk",
  "https://aqvcyyhuqcjnhohaclib.supabase.co/storage/v1/object/sign/categories/new_born_essentials_category.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81OWNhOGQyOC00MGM3LTQwOGEtYjZmOC04NjcxMmVmNzFhM2IiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJjYXRlZ29yaWVzL25ld19ib3JuX2Vzc2VudGlhbHNfY2F0ZWdvcnkuanBnIiwiaWF0IjoxNzU5MjA4Njc1LCJleHAiOjE3OTA3NDQ2NzV9.zJ5x3kBpD8iJ5koqBSYFOxqtKEpisVRkdBx1P1kz86Q"
]'::jsonb;

-- Check the results
SELECT id, name, images FROM products;
