#!/usr/bin/env node
// Generate Flipkart bulk-listing rows from the live catalog. Usage:
//   npm run flipkart:export -- --slug=coords-set-chinese-collar-soft-pear
//   npm run flipkart:export -- --all
// Writes a TSV to paste into the template at cell G5 (columns A-F are locked,
// Flipkart fills them) plus a report of everything a human still has to
// resolve. Never rewrites the .xls, because that would destroy its
// data-validation dropdowns and its colour-coded headers.
//
// The template itself (default: C_kids-apparel-combo_*.xls, gitignored) is
// downloaded from Flipkart Seller Hub -> Listings -> Bulk Upload -> the
// kids_apparel_combo category; it is not generated by this repo.

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
// Named/namespace imports from "xlsx" drop readFile/writeFile under Node's
// CJS interop (cjs-module-lexer doesn't statically see them) — default import
// gets the whole CommonJS module.exports object instead.
import XLSX from "xlsx";
import { COLUMN_COUNT, COLUMNS, columnIndex, FIRST_SELLER_COLUMN } from "../lib/flipkart/columns.ts";
import { CONFIG, placeholderFields } from "../lib/flipkart/config.ts";
import { mapProduct, MappingError } from "../lib/flipkart/mapping.ts";

const args = Object.fromEntries(
  process.argv.slice(2).map((arg) => {
    const [key, value] = arg.replace(/^--/, "").split("=");
    return [key, value ?? "1"];
  }),
);

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const DEFAULT_TEMPLATE = "C_kids-apparel-combo_6b8552c31ff94c26_1309-0947FK_REQOA2EHXFEXI.xls";
const TEMPLATE = args.template ?? DEFAULT_TEMPLATE;
// Resolved against the repo root, not process.cwd(), so the script works the
// same whether it's run from the repo root or from inside a subdirectory.
// path.resolve leaves an already-absolute --template path untouched.
const TEMPLATE_PATH = path.resolve(REPO_ROOT, TEMPLATE);
const SHEET = "kids_apparel_combo";
const FIRST_DATA_ROW = 4;
/** First seller-editable column: "Seller SKU ID", spreadsheet column G. */
const PASTE_FROM_INDEX = FIRST_SELLER_COLUMN;
const PASTE_FROM_CELL = `${String.fromCharCode(65 + PASTE_FROM_INDEX)}5`;
const BASE = (args.url ?? "https://cozyberries.in").replace(/\/$/, "");
const OUT_DIR = "exports/flipkart";

export const slugify = (s) =>
  s.toLowerCase().replace(/&/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

/**
 * Confirms the template's header row still matches the 69-column shape
 * `lib/flipkart/columns.ts` was built from. If Flipkart reissues the
 * template with a column inserted or renamed, every cell mapped by index
 * would silently land one column off and still pass QC with plausible but
 * wrong data — so this aborts loudly instead.
 */
export function assertTemplateShape(grid) {
  const expected = COLUMNS.map((c) => c.name);
  const header = grid?.[0] ?? [];
  for (let i = 0; i < expected.length; i++) {
    const actual = String(header[i] ?? "").trim();
    if (actual !== expected[i]) {
      throw new Error(
        `Template header mismatch at column ${i}: expected "${expected[i]}", found "${actual}". ` +
          "The template's column layout no longer matches lib/flipkart/columns.ts — " +
          "every later cell would land in the wrong column. Re-check the template " +
          "against columns.ts before mapping anything.",
      );
    }
  }
}

/** Existing SKU + Flipkart-hosted image URLs, keyed by slugified SKU. */
export function readTemplate(file) {
  const book = XLSX.readFile(file);
  const sheet = book.Sheets[SHEET];
  if (!sheet) throw new Error(`Sheet ${SHEET} not found in ${file}`);
  const grid = XLSX.utils.sheet_to_json(sheet, { header: 1, defval: "", raw: false });
  assertTemplateShape(grid);

  const skuColumn = columnIndex("Seller SKU ID");
  const imageColumns = [
    columnIndex("Main Image URL"),
    columnIndex("Other Image URL 1"),
    columnIndex("Other Image URL 2"),
    columnIndex("Other Image URL 3"),
  ];

  const rows = new Map();
  for (let i = FIRST_DATA_ROW; i < grid.length; i++) {
    const sku = String(grid[i]?.[skuColumn] ?? "").trim();
    if (!sku) continue;
    const images = imageColumns.map((c) => String(grid[i]?.[c] ?? "").trim()).filter(Boolean);
    rows.set(slugify(sku), { rowIndex: i, sku, images });
  }
  return rows;
}

export function titleCase(word) {
  return word.length ? word.charAt(0).toUpperCase() + word.slice(1) : word;
}

/**
 * The nearest-match colour substitution actually applied for this product, or
 * null if its base colour maps onto itself (an exact match, not a judgement
 * call). These pass Flipkart QC and land on a live product page, so the
 * report calls them out by name rather than folding them into "mapped OK".
 */
export function judgementCallFor(product, config) {
  const base = product.base_colors?.[0];
  if (!base) return null;
  const mapped = config.colourMap[base];
  if (!mapped || mapped === titleCase(base)) return null;
  return { base, mapped };
}

async function getJson(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`GET ${url} -> ${res.status}`);
  return res.json();
}

/** Pure report builder — no I/O, so it's unit-testable without a spreadsheet or network. */
export function buildReport({
  generatedAt,
  base,
  template,
  sheet,
  rowCount,
  config,
  blanks,
  unmappedOptional,
  judgementCalls,
  skipped,
  orphans,
  noTemplateRow = [],
  unmappedPrints = [],
  pasteCell = "G5",
  columnCount = 63,
}) {
  const placeholders = placeholderFields(config);
  // Fields filled in so no cell ships blank, but carrying an invented value the
  // EDIT_ME marker flags. These still block upload — a wrong manufacturer
  // address is a false legal declaration, not a cosmetic gap.
  const editMe = Object.entries(config)
    .filter(([, v]) => typeof v === "string" && v.includes("EDIT_ME"))
    .map(([k]) => k);
  const blocking = placeholders.length || editMe.length || blanks.size;
  return [
    "# Flipkart export report",
    "",
    `Generated ${generatedAt} from ${base}`,
    `Rows written: **${rowCount}**`,
    "",
    "## Paste instructions",
    "",
    "Do not paste this by hand. Run:",
    "",
    "    npm run flipkart:validate   # checks vocabulary, grouping, widths",
    "    npm run flipkart:write      # fills the template and writes the upload file",
    "",
    "and upload `exports/flipkart/kids-apparel-combo-upload.xls`.",
    "",
    `Pasting the ${columnCount} columns manually at ${pasteCell} is what failed QC on the first`,
    "attempt: every value landed one column right of where it belonged, so ACTIVE sat in",
    "MRP and the HSN in Luxury Cess. Writing the cells by index cannot drift that way.",
    "",
    "There is no CTRL+SHIFT+S macro to run — this template ships no VBA at all.",
    "",
    "## Must be fixed before upload",
    "",
    ...(blocking
      ? [
          ...placeholders.map((f) => `- config \`${f}\` is still a placeholder`),
          ...editMe.map(
            (f) => `- config \`${f}\` still contains EDIT_ME — the value is invented, replace it`,
          ),
          ...[...blanks].map(([name, n]) => `- mandatory column \`${name}\` is blank on ${n} row(s)`),
        ]
      : ["- none"]),
    "",
    "## Optional dropdown columns left blank",
    "",
    "Not upload-blocking, but a missed optional attribute is still a missed attribute —",
    "worth a look before assuming the listing is complete.",
    "",
    ...(unmappedOptional.size
      ? [...unmappedOptional].map(([name, n]) => `- \`${name}\` is blank on ${n} row(s)`)
      : ["- none"]),
    "",
    "## Judgement calls applied",
    "",
    "Nearest-match colour substitutions actually used in this run. These pass Flipkart",
    "QC and land on a live product page, so they need a human's eye, not just a blank check.",
    "",
    ...(judgementCalls.size
      ? [...judgementCalls].map(
          ([pair, slugs]) => `- ${pair} — ${[...slugs].sort().join(", ")}`,
        )
      : ["- none"]),
    "",
    "## Unverified config",
    "",
    "Not blank, not a placeholder — just never independently confirmed. Wrong package",
    "dimensions or weight cost money on every shipment; a brand string that doesn't",
    "match what's approved on Seller Hub fails QC on every row.",
    "",
    `- Default package: ${config.lengthCm} x ${config.breadthCm} x ${config.heightCm} cm @ ${config.weightKg} kg`,
    ...Object.entries(config.comboCategories)
      .filter(([, c]) => c.lengthCm ?? c.breadthCm ?? c.heightCm ?? c.weightKg)
      .map(
        ([slug, c]) =>
          `- ${slug} overrides it: ${c.lengthCm ?? config.lengthCm} x ${c.breadthCm ?? config.breadthCm} x ${c.heightCm ?? config.heightCm} cm @ ${c.weightKg ?? config.weightKg} kg`,
      ),
    `- Brand: ${config.brand}`,
    "",
    "## Skipped",
    "",
    ...(skipped.length ? skipped.map((s) => `- ${s}`) : ["- none"]),
    "",
    "## Prints with no mapped motif",
    "",
    "These fell back to the generic Pattern and left Pattern/Print Type blank,",
    "because their names read like colours rather than motifs — they may be solids.",
    "Add them to `printPatternMap` in lib/flipkart/config.ts once you know.",
    "",
    ...(unmappedPrints.length ? unmappedPrints.map((s) => `- ${s}`) : ["- none"]),
    "",
    "## Images",
    "",
    "Every image URL is one of our own originals (2000x2000 public JPEG), not the",
    "flixcart URL the template shipped with — those are Flipkart's re-processed",
    "copies, whose resolution and cropping we do not control. Flipkart accepts at",
    "most 4 per listing and re-downloads them at QC, so the URLs must stay public.",
    "",
    "## Products with no row in the template",
    "",
    "Exported anyway — they no longer need a template row, since the images come",
    "from our catalog. Listed only so the count is explainable.",
    "",
    ...(noTemplateRow.length ? noTemplateRow.map((s) => `- ${s}`) : ["- none"]),
    "",
    "## Template rows with no catalog match",
    "",
    "Renamed or junk. These are draft rows from an earlier snapshot; pasting over",
    "row 5 onward replaces them. Resolve by hand if any should be kept.",
    "",
    ...(orphans.length ? orphans.map((s) => `- ${s}`) : ["- none"]),
    "",
  ].join("\n");
}

async function main() {
  const existingRows = readTemplate(TEMPLATE_PATH);
  const catalog = await getJson(`${BASE}/api/catalog`);
  const bySlug = new Map(catalog.products.map((p) => [p.slug, p]));

  // --skus=a,b lets us re-export just the rows a previous upload left
  // unprocessed, without touching the ones Flipkart already approved.
  const onlySkus = args.skus ? new Set(args.skus.split(",").map((s) => s.trim())) : null;
  const wanted = args.all || onlySkus
    ? [...bySlug.keys()]
    : [args.slug].filter(Boolean);
  if (wanted.length === 0) {
    console.error("Pass --slug=<product-slug> or --all");
    process.exit(1);
  }

  const tsvRows = [];
  const skipped = [];
  const blanks = new Map();
  const unmappedOptional = new Map();
  const judgementCalls = new Map(); // "cream → Beige" -> Set<slug>
  const noTemplateRow = [];
  const unmappedPrintSet = new Set();

  for (const slug of wanted) {
    if (!bySlug.has(slug)) {
      skipped.push(`${slug} — not in the catalog`);
      continue;
    }
    // A missing template row is no longer disqualifying: images come from our
    // own originals, not from the row. Noted in the report, not skipped.
    const existing = existingRows.get(slug) ?? null;
    if (!existing) noTemplateRow.push(slug);
    const product = await getJson(`${BASE}/api/products/${slug}`).then((d) => d.product ?? d);
    const result = mapProduct(product, existing, CONFIG);
    if (result.status === "skipped") {
      skipped.push(`${slug} — ${result.reason}`);
      continue;
    }

    const jc = judgementCallFor(product, CONFIG);
    if (jc) {
      const key = `${jc.base} → ${jc.mapped}`;
      if (!judgementCalls.has(key)) judgementCalls.set(key, new Set());
      judgementCalls.get(key).add(slug);
    }

    for (const slug2 of product.color_slugs ?? []) {
      if (!CONFIG.printPatternMap[slug2]) unmappedPrintSet.add(slug2);
    }
    for (const row of result.rows) {
      if (onlySkus && !onlySkus.has(row.cells[columnIndex("Seller SKU ID")])) continue;
      if (row.cells.length !== COLUMN_COUNT) throw new Error(`bad row width for ${slug}`);
      // Our internal 69-column row, from Seller SKU ID onward. Placement into a
      // real template happens by header NAME in flipkart-write-xls.mjs, because
      // Flipkart reissues the template with columns inserted.
      tsvRows.push(row.cells.slice(FIRST_SELLER_COLUMN).join("\t"));
      for (const name of row.blanks) blanks.set(name, (blanks.get(name) ?? 0) + 1);
      for (const name of row.unmappedOptional) {
        unmappedOptional.set(name, (unmappedOptional.get(name) ?? 0) + 1);
      }
    }
  }

  // Template rows with no catalog product — renamed or junk, resolved by hand.
  const orphans = [...existingRows.entries()]
    .filter(([slug]) => !bySlug.has(slug))
    .map(([, row]) => `row ${row.rowIndex + 1}: ${row.sku}`);

  await mkdir(OUT_DIR, { recursive: true });
  await writeFile(path.join(OUT_DIR, "kids-apparel-combo.tsv"), tsvRows.join("\n") + "\n", "utf8");

  const unmappedPrints = [...unmappedPrintSet].sort();
  const report = buildReport({
    generatedAt: new Date().toISOString(),
    base: BASE,
    template: TEMPLATE,
    sheet: SHEET,
    rowCount: tsvRows.length,
    config: CONFIG,
    blanks,
    unmappedOptional,
    judgementCalls,
    skipped,
    orphans,
    noTemplateRow,
    unmappedPrints,
    pasteCell: PASTE_FROM_CELL,
    columnCount: COLUMN_COUNT - FIRST_SELLER_COLUMN,
  });
  await writeFile(path.join(OUT_DIR, "report.md"), report, "utf8");

  console.log(`Wrote ${tsvRows.length} row(s) to ${OUT_DIR}/kids-apparel-combo.tsv`);
  console.log(`Report: ${OUT_DIR}/report.md`);
  const editMe = Object.values(CONFIG).some((v) => typeof v === "string" && v.includes("EDIT_ME"));
  if (blanks.size || placeholderFields(CONFIG).length || editMe) {
    console.log("NOT upload-ready — see the report.");
    // A wrapper script must not be able to mistake this for a clean run.
    process.exitCode = 1;
  }
}

// Only run when invoked directly (`node`/`tsx scripts/flipkart-export.mjs`), not
// when a test imports this module for its pure helpers.
const isMain = process.argv[1] && import.meta.url === `file://${process.argv[1]}`;
if (isMain) {
  main().catch((err) => {
    if (err instanceof MappingError) console.error(`Mapping aborted: ${err.message}`);
    else console.error(err);
    process.exitCode = 1;
  });
}
